### PR TITLE
Adding Tor repos to always get the latest versions

### PR DESCRIPTION
**Pull request by OniriCorpe**
by default this package uses debian's Tor packets, which are wickedly and dangerously outdated

I modified the dependencies to acquire these packages via the Debian repos: `apt-transport-https obfs4proxy`
and these via the Tor repos: `tor tor-geoipdb deb.torproject.org-keyring`

I used this page as a resource to make this PR:
https://support.torproject.org/apt/tor-deb-repo/

> The Tor Project maintains its own [Debian package repository](https://deb.torproject.org/). Since Debian provides the LTS version of Tor, this might not always give you the latest stable Tor version. Therefore, it's recommended to install tor from our repository.

### CODE REVIEW

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
